/* Generated By:JavaCC: Do not edit this line. CALParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CALParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int SCOLON = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int ASIGN = 15;
  /** RegularExpression Id. */
  int OPBRA = 16;
  /** RegularExpression Id. */
  int CLBRA = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int TILDA = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int EQ = 23;
  /** RegularExpression Id. */
  int NOTEQ = 24;
  /** RegularExpression Id. */
  int LT = 25;
  /** RegularExpression Id. */
  int LTEQ = 26;
  /** RegularExpression Id. */
  int GT = 27;
  /** RegularExpression Id. */
  int GTEQ = 28;
  /** RegularExpression Id. */
  int VAR = 29;
  /** RegularExpression Id. */
  int CONST = 30;
  /** RegularExpression Id. */
  int RET = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int BOOL = 33;
  /** RegularExpression Id. */
  int VOID = 34;
  /** RegularExpression Id. */
  int MAIN = 35;
  /** RegularExpression Id. */
  int IF = 36;
  /** RegularExpression Id. */
  int ELSE = 37;
  /** RegularExpression Id. */
  int TRUE = 38;
  /** RegularExpression Id. */
  int FALSE = 39;
  /** RegularExpression Id. */
  int WHILE = 40;
  /** RegularExpression Id. */
  int BEGIN = 41;
  /** RegularExpression Id. */
  int END = 42;
  /** RegularExpression Id. */
  int IS = 43;
  /** RegularExpression Id. */
  int SKI = 44;
  /** RegularExpression Id. */
  int IDENTIFIER = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int SPECHAR = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\" \"",
    "\"\\f\"",
    "\"/*\"",
    "<token of kind 8>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 11>",
    "\",\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"variable\"",
    "\"constant\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "\"is\"",
    "\"skip\"",
    "<IDENTIFIER>",
    "<DIGIT>",
    "<LETTER>",
    "\"_\"",
  };

}
